"""adicionar campo estoque

Revision ID: c77314fae88a
Revises: 7e7bfa9df78b
Create Date: 2026-04-27 21:49:01.361812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77314fae88a'
down_revision = '7e7bfa9df78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estoque', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('estoque')

    # ### end Alembic commands ###
